language: php

php:
  - '7.0'
  - hhvm # on Trusty only
  - nightly
  
deploy:
  provider: releases
  api_key:
    secure: KmKwmt...[REDACTED]...LPE=
  file: class-xml-file.phar
  skip_cleanup: true
  on:
    tags: true
    repo: release/class-xml-file  
