language: php

php:
  - '7.2'

  
script: phpunit --bootstrap src/autoload.php --test-suffix '-test.php,Test.php,.phpt' tests

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    secure: KmKwmt...[REDACTED]...LPE=
  file: class-xml-file.phar
  skip_cleanup: true
  on:
    tags: true
    repo: release/class-xml-file  
